
import {BrowserAnimationsModule} from '@angular/platform-browser/animations';
import { NgModule } from '@angular/core';
import {MatCardModule ,
  MatButtonModule, 
  MatFormFieldModule,  
  MatAutocompleteModule,
  MatToolbarModule, 
  MatExpansionModule, 
  MatGridListModule,
  MatInputModule,
  MatSelectModule,
  MatIconModule,
  MatTabsModule,
  MatRadioModule,
  MatSnackBarModule,
  MatProgressSpinnerModule,
  MatTableModule,
  MatProgressBarModule,
  MatDialogModule,
  MatDialog,
  MatDialogRef,
  MatStepperModule,  
  MatMenuModule,
  MatCheckboxModule,
  MatSidenavModule,
  MatTooltipModule,
  MatPaginatorModule,
  MatSlideToggleModule
} from '@angular/material';

import { Validators } from '@angular/forms';
@NgModule({
  imports: [
    MatButtonModule, 
    MatTooltipModule,
    BrowserAnimationsModule,  
    MatAutocompleteModule,
    MatPaginatorModule,
    MatToolbarModule,
    MatSnackBarModule,
    MatProgressBarModule,
    MatExpansionModule,  
    MatGridListModule,
    MatRadioModule,
    MatCardModule,
    MatSidenavModule,
    MatProgressSpinnerModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatIconModule,
    MatTabsModule,
    MatTableModule,
    MatDialogModule,
    MatStepperModule, 
    MatMenuModule,
    MatCheckboxModule
  ],
  exports: [
    MatButtonModule, 
    MatTooltipModule,
    MatSidenavModule,
    BrowserAnimationsModule, 
    MatToolbarModule,
    MatCheckboxModule,
    MatCardModule,
    MatExpansionModule,
    MatSnackBarModule, 
    MatPaginatorModule,
    MatGridListModule,
    MatRadioModule,
    MatProgressSpinnerModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatIconModule,
    MatTabsModule,
    MatTableModule,
    MatProgressBarModule,
    MatAutocompleteModule,
    MatDialogModule,
    MatStepperModule, 
    MatMenuModule
  ],
})
export class MaterialModule { }